version: '3'

networks:
  backend:
    driver: bridge

services:
  symfony-nginx:
    build:
      context: .docker/symfony_nginx
    volumes:
      - './symfony:/var/www/html'
    restart: always
    ports:
      - "8089:80"
    networks:
      - backend

  symfony:
    build:
      context: .docker/symfony
    environment:
      - PHP_IDE_CONFIG="serverName=symfony.local"
      - PHP_IDE_CONFIG=serverName=symfony.local
      - AUTH_TOKEN=ba67df6a-a17c-476f-8e95-bcdb75ed3958
      - APP_DEBUG=0
    volumes:
      - './symfony:/var/www/html'
    restart: always
    ports:
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint:
      - /bin/bash
      - -c
      - |
        composer install --working-dir=/var/www/html --no-dev --optimize-autoloader \
        && php-fpm
    networks:
      - backend

volumes:
  code: